app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8080:8080"
  volumes:
    - .:/root/GetStartedSwift
  command: bash -c "cd /root/GetStartedSwift && swift build --clean && swift build && swift test && ./.build/debug/kitura-helloworld"
